class Constants:
    LIKE_QUERY_ID = "lI07N6Otwv1PhnEgXILM7A"
    RETWEET_QUERY_ID = "ojPdsZsimiJrUGLR1sjUtA"
    TWEET_QUERY_ID = "IVdJU2Vjw2llhmJOAZy9Ow"
    BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA"

    def __init__(self):
        self.LIKE_QUERY_ID = "lI07N6Otwv1PhnEgXILM7A"
        self.RETWEET_QUERY_ID = "ojPdsZsimiJrUGLR1sjUtA"
        self.TWEET_QUERY_ID = "IVdJU2Vjw2llhmJOAZy9Ow"
        self.BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA"
